### ISSUE TITLE
Change password form does not work

### ISSUE THREAD

**Issue by Tsjippy** [glowlogix/wp-frontend-profile#57] opened 2020-06-11 19:13 UTC
**Describe the bug**
When I fill in a new password in the password tab, and click update password, the form reloads, but my password in not changed.

**Steps to Reproduce**

1. Go to the page containing the [wpfep] shortcode
2. Click on the password tab
3. Fill in a password that complies o all requirements
4. Confirm the new password
5. Click "Update password"
6. The page reloads, but the password is not changed.

**Expected behavior**
I should get a confirmation message stating that my password is changed.
When I login again, I should use the new password.

**Screenshots**

**Environment information**
 - Device: laptop/iphone
 - OS: all oses
 - Browser and version: all browsers
 - Plugins and version:WP Frontend Profile 1.2.2
 - Theme and version: Orfeo 1.0.6

**Comment by mfaizanrasool** [comment] 2020-06-16 05:48
The issue is fixed in this pull request
https://github.com/glowlogix/wp-frontend-profile/pull/58

**Comment by musamamasood** [comment] 2020-11-24 17:16
The issue has been fixed in v1.2.3

**Closed by musamamasood** 2020-11-24 17:16 UTC
Labels: bug
